name: buldm_frontend
description: A Flutter project for building a frontend application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add your project dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Add assets and other configurations here if needed
